name: Build and Push Container
on: [push]
jobs:
  build-push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build tag from branch name
        run: echo ::set-output name=tag::jaypickle/godot-build:${GITHUB_REF##*/}
        id: tag
      - uses: elgohr/Publish-Docker-Github-Action@v2.10
        with:
          name: ${{ steps.tag.outputs.tag }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
